### ISSUE TITLE
Repository pattern defining and usage

### ISSUE THREAD

**Issue by Ahmad-Hamwi** [Amrjyniat/Meals#1]
Hi Amr, I have noticed that you have your repository implementation is defined in you domain layer, and the class MainRepositoryImpl is referencing everything from the data layer. I Believe that its correct place is at the data layer.

Also, I have noticed that you are trying to inject the implementation directly. You can inject the interface, and let Hilt inject you implementation at runtime.

**Comment by Amrjyniat** [comment]
Hi Ahmad, sorry for the late response.
You're right, I'll fix it soon, Thank you!
